/**
 * Campus Runner — Seed Data for 2-Hostel, 6-Vendor Pilot
 */

import { HostelBlock, Vendor, User, Role, Order, OrderStatus, SlotWindow, CampusSettings, Settlement } from './types';

export const SEED_HOSTELS: HostelBlock[] = [
  {
    id: 'hostel-1',
    code: 'BLOCK_A',
    name: 'Aryabhatta Hall (Block A)',
    vegOnlyEnforced: false,
    distanceTier: 'SAME_ZONE',
    roomsCount: 240,
  },
  {
    id: 'hostel-2',
    code: 'BLOCK_B',
    name: 'Bhaskara Hall (Block B — Strict Veg)',
    vegOnlyEnforced: true, // HARD RULE: Vegetarian only enforced for this hostel!
    distanceTier: 'CROSS_CAMPUS',
    roomsCount: 210,
  },
];

export const SEED_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Chai & Maggi Point',
    location: 'Food Court A, Stall 1',
    ownerPhone: '9870011221',
    commissionPct: 10,
    isActive: true,
    fssaiNumber: '20822003001421',
    cuisineTag: 'Comfort Food & Tea',
    rating: 4.8,
    reviewCount: 342,
    bannerColor: 'from-amber-500/20 to-orange-500/10',
    prepTimeMinutes: 12,
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    menuItems: [
      {
        id: 'm1-1',
        vendorId: 'vendor-1',
        name: 'Classic Masala Maggi',
        price: 45,
        isVeg: true,
        isAvailable: true,
        category: 'snacks',
        description: 'Double-tastemaker spiced Maggi with tossed sweet peas and onions.',
        image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '10 min',
        tags: ['Hot 🔥', 'Bestseller ⭐'],
      },
      {
        id: 'm1-2',
        vendorId: 'vendor-1',
        name: 'Cheese Corn Burst Maggi',
        price: 70,
        isVeg: true,
        isAvailable: true,
        category: 'snacks',
        description: 'Topped with melted Amul mozzarella and butter sweet corn.',
        image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '12 min',
        tags: ['Cheesy 🧀'],
      },
      {
        id: 'm1-3',
        vendorId: 'vendor-1',
        name: 'Double Egg Bread Omelette',
        price: 65,
        isVeg: false, // NON-VEG
        isAvailable: true,
        category: 'breakfast',
        description: 'Fluffy 2-egg masala omelette stuffed between toasted butter bread.',
        image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&auto=format&fit=crop&q=80',
        rating: 4.7,
        prepTime: '10 min',
        tags: ['Protein 🥚'],
      },
      {
        id: 'm1-4',
        vendorId: 'vendor-1',
        name: 'Irani Adrak Chai (2 Cups Flask)',
        price: 35,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Brewed with fresh pounded ginger and crushed green cardamom.',
        image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '5 min',
        tags: ['Hot ☕'],
      },
      {
        id: 'm1-5',
        vendorId: 'vendor-1',
        name: 'Crispy Punjabi Samosa (2 Pcs)',
        price: 30,
        isVeg: true,
        isAvailable: true,
        category: 'snacks',
        description: 'Served with mint-coriander green chutney and tamarind saunth.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
        rating: 4.6,
        prepTime: '8 min',
        tags: ['Crispy 🥟'],
      },
      {
        id: 'm1-6',
        vendorId: 'vendor-1',
        name: 'Warm Bun Maska Jam',
        price: 40,
        isVeg: true,
        isAvailable: true,
        category: 'breakfast',
        description: 'Fresh bakery bun slathered with salted butter and mixed fruit jam.',
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80',
        rating: 4.7,
        prepTime: '6 min',
        tags: ['Sweet 🍞'],
      },
    ],
  },
  {
    id: 'vendor-2',
    name: 'Kathiawar Dosa Stall',
    location: 'Food Court A, Stall 3',
    ownerPhone: '9870011222',
    commissionPct: 10,
    isActive: true,
    fssaiNumber: '20822003001899',
    cuisineTag: 'South Indian & Crispy Dosas',
    rating: 4.7,
    reviewCount: 289,
    bannerColor: 'from-emerald-500/20 to-teal-500/10',
    prepTimeMinutes: 15,
    coverImage: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=80',
    menuItems: [
      {
        id: 'm2-1',
        vendorId: 'vendor-2',
        name: 'Mysore Butter Masala Dosa',
        price: 90,
        isVeg: true,
        isAvailable: true,
        category: 'meal',
        description: 'Crisp crepe lined with spicy red chili-garlic paste and spiced potato filling.',
        image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '15 min',
        tags: ['Bestseller ⭐', 'Crispy 🥞'],
      },
      {
        id: 'm2-2',
        vendorId: 'vendor-2',
        name: 'Paneer Cheese Uttapam',
        price: 110,
        isVeg: true,
        isAvailable: true,
        category: 'meal',
        description: 'Thick fermented rice pancake topped with fresh diced paneer and onions.',
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
        rating: 4.7,
        prepTime: '15 min',
        tags: ['Chef Special 👨‍🍳'],
      },
      {
        id: 'm2-3',
        vendorId: 'vendor-2',
        name: 'Steamed Idli Sambhar (3 Pcs)',
        price: 55,
        isVeg: true,
        isAvailable: true,
        category: 'breakfast',
        description: 'Pillowy soft idlis served with piping hot drumstick sambhar and coconut chutney.',
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '8 min',
        tags: ['Healthy 🍃'],
      },
      {
        id: 'm2-4',
        vendorId: 'vendor-2',
        name: 'Crispy Medu Vada (2 Pcs)',
        price: 50,
        isVeg: true,
        isAvailable: true,
        category: 'breakfast',
        description: 'Golden fried lentil donuts with crushed peppercorns and curry leaves.',
        image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?w=500&auto=format&fit=crop&q=80',
        rating: 4.6,
        prepTime: '10 min',
        tags: ['Crunchy 🥯'],
      },
      {
        id: 'm2-5',
        vendorId: 'vendor-2',
        name: 'South Indian Filter Kaapi',
        price: 30,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Authentic chicory-blend frothed strong filter decoction with rich milk.',
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '5 min',
        tags: ['Must Try ☕'],
      },
    ],
  },
  {
    id: 'vendor-3',
    name: 'Campus Bakers & Cafe',
    location: 'Central Library Walkway',
    ownerPhone: '9870011223',
    commissionPct: 12,
    isActive: true,
    fssaiNumber: '20822003002102',
    cuisineTag: 'Artisan Sandwiches & Bakery',
    rating: 4.9,
    reviewCount: 412,
    bannerColor: 'from-amber-600/20 to-yellow-500/10',
    prepTimeMinutes: 10,
    coverImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    menuItems: [
      {
        id: 'm3-1',
        vendorId: 'vendor-3',
        name: 'Bombay Veg Grilled Club Sandwich',
        price: 85,
        isVeg: true,
        isAvailable: true,
        category: 'snacks',
        description: '3-layer jumbo bread filled with spiced potato, cucumber, tomato, and mint chutney.',
        image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '10 min',
        tags: ['Bestseller ⭐'],
      },
      {
        id: 'm3-2',
        vendorId: 'vendor-3',
        name: 'Tandoori Chicken Tikka Sub',
        price: 130,
        isVeg: false, // NON-VEG
        isAvailable: true,
        category: 'meal',
        description: 'Smoky chicken breast cubes in chipotle-tandoori spread with crunchy iceberg.',
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '12 min',
        tags: ['Smoky 🍗'],
      },
      {
        id: 'm3-3',
        vendorId: 'vendor-3',
        name: 'Golden Egg Puff (2 Pcs)',
        price: 50,
        isVeg: false, // NON-VEG
        isAvailable: true,
        category: 'snacks',
        description: 'Flaky pastry stuffed with curried boiled egg halves and caramelized onions.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
        rating: 4.6,
        prepTime: '5 min',
        tags: ['Flaky 🥐'],
      },
      {
        id: 'm3-4',
        vendorId: 'vendor-3',
        name: 'Chilled Thick Cold Coffee',
        price: 60,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Creamy blended iced coffee with chocolate drizzle.',
        image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '5 min',
        tags: ['Chilled 🥤'],
      },
      {
        id: 'm3-5',
        vendorId: 'vendor-3',
        name: 'Warm Choco Lava Cake',
        price: 75,
        isVeg: true,
        isAvailable: true,
        category: 'bakery',
        description: 'Molten Belgian chocolate center that flows on the first spoon.',
        image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '8 min',
        tags: ['Decadent 🍫'],
      },
      {
        id: 'm3-6',
        vendorId: 'vendor-3',
        name: 'Fudgy Walnut Brownie',
        price: 65,
        isVeg: true,
        isAvailable: true,
        category: 'bakery',
        description: 'Dark cocoa cake loaded with toasted California walnuts.',
        image: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '5 min',
        tags: ['Fudgy 🍫'],
      },
    ],
  },
  {
    id: 'vendor-4',
    name: 'Night Canteen - Paratha Junction',
    location: 'Student Activity Center Ground Floor',
    ownerPhone: '9870011224',
    commissionPct: 10,
    isActive: true,
    fssaiNumber: '20822003003044',
    cuisineTag: 'North Indian Parathas & Rolls',
    rating: 4.6,
    reviewCount: 520,
    bannerColor: 'from-red-500/20 to-orange-600/10',
    prepTimeMinutes: 18,
    coverImage: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&auto=format&fit=crop&q=80',
    menuItems: [
      {
        id: 'm4-1',
        vendorId: 'vendor-4',
        name: 'Amritsari Aloo Pyaaz Paratha (2 Pcs)',
        price: 80,
        isVeg: true,
        isAvailable: true,
        category: 'meal',
        description: 'Stuffed whole wheat tawa flatbread served with fresh spiced curd and mixed pickle.',
        image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '15 min',
        tags: ['Late Night 🌙', 'Bestseller ⭐'],
      },
      {
        id: 'm4-2',
        vendorId: 'vendor-4',
        name: 'Dhaba Paneer Paratha with Butter',
        price: 110,
        isVeg: true,
        isAvailable: true,
        category: 'meal',
        description: 'Generously stuffed with crushed malai paneer, chopped green chillies, and coriander.',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
        rating: 4.7,
        prepTime: '15 min',
        tags: ['Rich 🧈'],
      },
      {
        id: 'm4-3',
        vendorId: 'vendor-4',
        name: 'Double Egg Masala Kathi Roll',
        price: 85,
        isVeg: false, // NON-VEG
        isAvailable: true,
        category: 'meal',
        description: 'Flaky paratha rolled with spiced eggs, diced onions, and chaat masala.',
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=80',
        rating: 4.6,
        prepTime: '12 min',
        tags: ['Quick Bite 🌯'],
      },
      {
        id: 'm4-4',
        vendorId: 'vendor-4',
        name: 'Chicken Kebab Malai Roll',
        price: 125,
        isVeg: false, // NON-VEG
        isAvailable: true,
        category: 'meal',
        description: 'Juicy seekh kebab skewers with creamy mint mayo wrapped hot.',
        image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '15 min',
        tags: ['Juicy 🌯'],
      },
      {
        id: 'm4-5',
        vendorId: 'vendor-4',
        name: 'Sweet Punjabi Malai Lassi',
        price: 45,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Churned thick curd topped with saffron essence and almond flakes.',
        image: 'https://images.unsplash.com/photo-1571006682858-a458b8a69288?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '5 min',
        tags: ['Refreshing 🥛'],
      },
    ],
  },
  {
    id: 'vendor-5',
    name: 'Juice & Shake Corner',
    location: 'Sports Complex Gate 2',
    ownerPhone: '9870011225',
    commissionPct: 8,
    isActive: true,
    fssaiNumber: '20822003004118',
    cuisineTag: 'Fresh Juices & Protein Shakes',
    rating: 4.8,
    reviewCount: 198,
    bannerColor: 'from-lime-500/20 to-emerald-500/10',
    prepTimeMinutes: 8,
    coverImage: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=800&auto=format&fit=crop&q=80',
    menuItems: [
      {
        id: 'm5-1',
        vendorId: 'vendor-5',
        name: 'Fresh Mosambi (Sweet Lime) Juice',
        price: 50,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Pure 100% cold pressed juice with a pinch of rock salt and roasted cumin.',
        image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '5 min',
        tags: ['Pure Juice 🍊'],
      },
      {
        id: 'm5-2',
        vendorId: 'vendor-5',
        name: 'Alphonso Mango Thick Shake',
        price: 70,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Blended with real mango pulp, whole milk, and vanilla ice cream scoop.',
        image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '6 min',
        tags: ['Bestseller ⭐'],
      },
      {
        id: 'm5-3',
        vendorId: 'vendor-5',
        name: 'Gym-Bro Peanut Butter Banana Shake',
        price: 85,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Packed with 18g natural protein: roasted peanut butter, chia seeds, and oats.',
        image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '8 min',
        tags: ['High Protein 💪'],
      },
      {
        id: 'm5-4',
        vendorId: 'vendor-5',
        name: 'Seasonal Fresh Fruit Chaat Bowl',
        price: 60,
        isVeg: true,
        isAvailable: true,
        category: 'snacks',
        description: 'Diced papaya, apple, pomegranate, and pineapple with tangy lemon masala.',
        image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&auto=format&fit=crop&q=80',
        rating: 4.7,
        prepTime: '8 min',
        tags: ['Healthy 🥗'],
      },
    ],
  },
  {
    id: 'vendor-6',
    name: 'South Indian Tiffin Hub',
    location: 'Engineering Block Plaza',
    ownerPhone: '9870011226',
    commissionPct: 10,
    isActive: true,
    fssaiNumber: '20822003005221',
    cuisineTag: 'Quick Rice & Tiffin Meals',
    rating: 4.7,
    reviewCount: 310,
    bannerColor: 'from-orange-500/20 to-yellow-600/10',
    prepTimeMinutes: 12,
    coverImage: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    menuItems: [
      {
        id: 'm6-1',
        vendorId: 'vendor-6',
        name: 'Lemon Rice with Fried Peanuts & Papad',
        price: 75,
        isVeg: true,
        isAvailable: true,
        category: 'meal',
        description: 'Tangy turmeric tempered rice with mustard seeds, curry leaves, and crunchy papad.',
        image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=500&auto=format&fit=crop&q=80',
        rating: 4.7,
        prepTime: '10 min',
        tags: ['Tangy 🍋'],
      },
      {
        id: 'm6-2',
        vendorId: 'vendor-6',
        name: 'Curd Rice with Pomegranate Tadka',
        price: 70,
        isVeg: true,
        isAvailable: true,
        category: 'meal',
        description: 'Cool comfort food: set curd, ginger, green chili tadka, and fresh coriander.',
        image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '8 min',
        tags: ['Comfort 🍚'],
      },
      {
        id: 'm6-3',
        vendorId: 'vendor-6',
        name: 'Ghee Podi Roast Dosa',
        price: 95,
        isVeg: true,
        isAvailable: true,
        category: 'meal',
        description: 'Crisped with pure cow ghee and dusted with aromatic spicy gunpowder podi.',
        image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500&auto=format&fit=crop&q=80',
        rating: 4.9,
        prepTime: '12 min',
        tags: ['Ghee Roast 🧈'],
      },
      {
        id: 'm6-4',
        vendorId: 'vendor-6',
        name: 'Spiced Masala Chaas (Buttermilk)',
        price: 25,
        isVeg: true,
        isAvailable: true,
        category: 'beverage',
        description: 'Refreshing churned spiced buttermilk with mint and asafoetida.',
        image: 'https://images.unsplash.com/photo-1571006682858-a458b8a69288?w=500&auto=format&fit=crop&q=80',
        rating: 4.8,
        prepTime: '3 min',
        tags: ['Cooling 🥛'],
      },
    ],
  },
];

export const SEED_USERS: User[] = [
  // 3 Students
  {
    id: 'student-1',
    role: Role.STUDENT,
    name: 'Aarav Sharma',
    phone: '9876543210',
    hostelBlock: 'Aryabhatta Hall (Block A)',
    roomNumber: 'A-204',
    isVerified: true,
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'student-2',
    role: Role.STUDENT,
    name: 'Priya Patel',
    phone: '9876543211',
    hostelBlock: 'Bhaskara Hall (Block B — Strict Veg)',
    roomNumber: 'B-112',
    isVerified: true,
    createdAt: '2026-09-02T09:30:00Z',
  },
  {
    id: 'student-3',
    role: Role.STUDENT,
    name: 'Rohan Verma',
    phone: '9876543212',
    hostelBlock: 'Aryabhatta Hall (Block A)',
    roomNumber: 'A-318',
    isVerified: true,
    createdAt: '2026-09-03T11:15:00Z',
  },

  // 2 Runners
  {
    id: 'runner-1',
    role: Role.RUNNER,
    name: 'Vikram Singh',
    phone: '9811122233',
    hostelBlock: 'Bhaskara Hall (Block B — Strict Veg)',
    roomNumber: 'B-405',
    isVerified: true,
    createdAt: '2026-09-01T10:00:00Z',
  },
  {
    id: 'runner-2',
    role: Role.RUNNER,
    name: 'Aniket Deshmukh',
    phone: '9822233344',
    hostelBlock: 'Aryabhatta Hall (Block A)',
    roomNumber: 'A-108',
    isVerified: true,
    createdAt: '2026-09-02T12:00:00Z',
  },

  // 1 Admin
  {
    id: 'admin-1',
    role: Role.ADMIN,
    name: 'Prof. S. Ranganathan (Chief Warden)',
    email: 'admin@campus.ac.in',
    isVerified: true,
    createdAt: '2026-08-15T00:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-7801',
    studentId: 'student-1',
    studentName: 'Aarav Sharma',
    studentPhone: '9876543210',
    vendorId: 'vendor-1',
    vendorName: 'Chai & Maggi Point',
    slot: SlotWindow.NIGHT,
    hostelBlock: 'Aryabhatta Hall (Block A)',
    roomNumber: 'A-204',
    subtotalAmount: 115,
    deliveryFee: 15,
    totalAmount: 130,
    commissionAmt: 13,
    status: OrderStatus.OUT_FOR_DELIVERY,
    isVegOnly: false,
    otpCode: '4829', // Handover OTP shown to student, entered by runner
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    runnerId: 'runner-1',
    runnerName: 'Vikram Singh',
    pickedUpAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'oi-1',
        orderId: 'ORD-7801',
        menuItemId: 'm1-1',
        name: 'Classic Masala Maggi',
        priceEach: 45,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi-2',
        orderId: 'ORD-7801',
        menuItemId: 'm1-2',
        name: 'Cheese Corn Burst Maggi',
        priceEach: 70,
        quantity: 1,
        isVeg: true,
      },
    ],
  },
  {
    id: 'ORD-7802',
    studentId: 'student-2',
    studentName: 'Priya Patel',
    studentPhone: '9876543211',
    vendorId: 'vendor-2',
    vendorName: 'Kathiawar Dosa Stall',
    slot: SlotWindow.NIGHT,
    hostelBlock: 'Bhaskara Hall (Block B — Strict Veg)',
    roomNumber: 'B-112',
    subtotalAmount: 140,
    deliveryFee: 25,
    totalAmount: 165,
    commissionAmt: 14,
    status: OrderStatus.PREPARING,
    isVegOnly: true,
    otpCode: '7392',
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'oi-3',
        orderId: 'ORD-7802',
        menuItemId: 'm2-1',
        name: 'Mysore Butter Masala Dosa',
        priceEach: 90,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi-4',
        orderId: 'ORD-7802',
        menuItemId: 'm2-4',
        name: 'Crispy Medu Vada (2 Pcs)',
        priceEach: 50,
        quantity: 1,
        isVeg: true,
      },
    ],
  },
  {
    id: 'ORD-7803',
    studentId: 'student-3',
    studentName: 'Rohan Verma',
    studentPhone: '9876543212',
    vendorId: 'vendor-4',
    vendorName: 'Night Canteen - Paratha Junction',
    slot: SlotWindow.NIGHT,
    hostelBlock: 'Aryabhatta Hall (Block A)',
    roomNumber: 'A-318',
    subtotalAmount: 125,
    deliveryFee: 15,
    totalAmount: 140,
    commissionAmt: 13,
    status: OrderStatus.PLACED,
    isVegOnly: false,
    otpCode: '1945',
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    items: [
      {
        id: 'oi-5',
        orderId: 'ORD-7803',
        menuItemId: 'm4-1',
        name: 'Amritsari Aloo Pyaaz Paratha (2 Pcs)',
        priceEach: 80,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi-6',
        orderId: 'ORD-7803',
        menuItemId: 'm4-5',
        name: 'Sweet Punjabi Malai Lassi',
        priceEach: 45,
        quantity: 1,
        isVeg: true,
      },
    ],
  },
  {
    id: 'ORD-7798',
    studentId: 'student-1',
    studentName: 'Aarav Sharma',
    studentPhone: '9876543210',
    vendorId: 'vendor-3',
    vendorName: 'Campus Bakers & Cafe',
    slot: SlotWindow.EVENING,
    hostelBlock: 'Aryabhatta Hall (Block A)',
    roomNumber: 'A-204',
    subtotalAmount: 145,
    deliveryFee: 15,
    totalAmount: 160,
    commissionAmt: 17,
    status: OrderStatus.DELIVERED,
    isVegOnly: false,
    otpCode: '8812',
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    runnerId: 'runner-1',
    runnerName: 'Vikram Singh',
    pickedUpAt: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 2.2 * 3600 * 1000).toISOString(),
    items: [
      {
        id: 'oi-7',
        orderId: 'ORD-7798',
        menuItemId: 'm3-1',
        name: 'Bombay Veg Grilled Club Sandwich',
        priceEach: 85,
        quantity: 1,
        isVeg: true,
      },
      {
        id: 'oi-8',
        orderId: 'ORD-7798',
        menuItemId: 'm3-4',
        name: 'Chilled Thick Cold Coffee',
        priceEach: 60,
        quantity: 1,
        isVeg: true,
      },
    ],
  },
];

export const INITIAL_SETTLEMENTS: Settlement[] = [
  {
    id: 'stl-1',
    vendorId: 'vendor-1',
    vendorName: 'Chai & Maggi Point',
    periodStart: '2026-09-20T00:00:00Z',
    periodEnd: '2026-09-20T23:59:59Z',
    grossAmt: 4250,
    commissionAmt: 425,
    netPayable: 3825,
    ordersCount: 38,
    paidAt: '2026-09-21T09:00:00Z',
  },
  {
    id: 'stl-2',
    vendorId: 'vendor-2',
    vendorName: 'Kathiawar Dosa Stall',
    periodStart: '2026-09-20T00:00:00Z',
    periodEnd: '2026-09-20T23:59:59Z',
    grossAmt: 3890,
    commissionAmt: 389,
    netPayable: 3501,
    ordersCount: 29,
    paidAt: '2026-09-21T09:00:00Z',
  },
];

export const INITIAL_SETTINGS: CampusSettings = {
  globalOrderingPaused: false,
  cutoffTime: '21:15', // 9:15 PM
  upiVpa: 'campusrunner@icici',
  upiName: 'Campus Runner Pilot',
  pausedHostelBlocks: [], // empty by default
};
